### ISSUE TITLE
Use webfont with other element than <i>

### ISSUE THREAD

**Issue by jbelien** [mono-company/mono-icons#3]
*This is not an issue, just a question!*

I noticed you force the use of the `<i>` element with [`i[class^="icon-"]`](https://github.com/mono-company/mono-icons/blob/master/iconfont/icons.css#L10).
I know this is usually the HTML element used with webfont but what if I want to use my `icon-*` class on another HTML element (`<span class="icon-add"></span>`, for instance).

**Comment by Wolfr** [comment]
This is baked-in to the code, this is quite common in other frameworks.

I don't really see a reason to use another element. We could theoretically use an universal selector in our stylesheet, but this would then lead to (a) more chances of breakage and (b) possibly worse performance due to the use of the universal selector. 

What I do think would be helpful, is that we namespace our icons a bit more than they are now to avoid clashes with other libaries (e.g. `mi mi-something`) (@evajacobs )

**Comment by jbelien** [comment]
> I don't really see a reason to use another element.

I completely agree with you. I just had the issue that a Leaflet plugin I use was using `<span>` element by default ([fixed](https://github.com/jbelien/osm-report/commit/ef53f6962b590a751935c4831363fce2ab33dbb7#diff-7aefdf84e1f1f2461a36593a41217617R27)).

> What I do think would be helpful, is that we namespace our icons a bit more than they are now to avoid clashes with other libaries (e.g. mi mi-something) (@evajacobs )

I like the namespace idea 👍
